if (localStorage.getItem("savedGameData")) {
  window.data = JSON.parse(localStorage.getItem("savedGameData"));
} else {
  window.data = {
    coffee: 100,
    totalCPS: 0,
    producers: [
      {
        id: "chemex",
        price: 5,
        previousPrice: [],
        unlocked: false,
        cps: 20,
        qty: 0,
      },
      {
        id: "french_press",
        price: 25,
        previousPrice: [],
        unlocked: false,
        cps: 40,
        qty: 0,
      },
      {
        id: "mr._coffee",
        price: 50,
        previousPrice: [],
        unlocked: false,
        cps: 100,
        qty: 0,
      },
      {
        id: "ten_cup_urn",
        price: 250,
        previousPrice: [],
        unlocked: false,
        cps: 200,
        qty: 0,
      },
      {
        id: "espresso_machine",
        price: 500,
        previousPrice: [],
        unlocked: false,
        cps: 400,
        qty: 0,
      },
      {
        id: "ten_gallon_urn",
        price: 2500,
        previousPrice: [],
        unlocked: false,
        cps: 1000,
        qty: 0,
      },
      {
        id: "coffeeshop",
        price: 5000,
        previousPrice: [],
        unlocked: false,
        cps: 1500,
        qty: 0,
      },
      {
        id: "coffee_factory",
        price: 25000,
        previousPrice: [],
        unlocked: false,
        cps: 2000,
        qty: 0,
      },
      {
        id: "coffee_fountain",
        price: 50000,
        previousPrice: [],
        unlocked: false,
        cps: 4000,
        qty: 0,
      },
      {
        id: "coffee_river",
        price: 250000,
        previousPrice: [],
        unlocked: false,
        cps: 10000,
        qty: 0,
      },
      {
        id: "coffee_ocean",
        price: 500000,
        previousPrice: [],
        unlocked: false,
        cps: 20000,
        qty: 0,
      },
      {
        id: "coffee_planet",
        price: 50,
        previousPrice: [],
        unlocked: false,
        cps: 40000,
        qty: 0,
      },
    ],
  };
}
